config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  get '/login'    => 'sessions#new'
  post '/login'   => 'sessions#create'
  get '/logout'   => 'sessions#destroy'
  get '/timeline' => 'users#timeline'
  get '/mentions' => 'users#mentions'

  resources :users, only: [:new, :create] do
    member do
      post 'follow'
      post 'unfollow'
    end
  end

  resources :hashtags, only: :show

  resources :statuses, only: [:new, :create] do
    member do
      post 'retweet'
    end
  end
  get '/:username' => 'users#show', as: 'user'
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :user
  belongs_to :status

  def mark_viewed!
    self.update(viewed_at: Time.now)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: :User, foreign_key: :follower_id
  belongs_to :leader, class_name: :User, foreign_key: :leader_id
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :creator, foreign_key: 'user_id', class_name: :User
  belongs_to :parent_status, class_name: :Status, foreign_key: 'retweet_id'

  validates :creator, presence: true
  validates :body, presence: true, length: {minimum: 5}

  after_save :extract_mentions

  def extract_mentions
    mentions = self.body.scan(/@(\w+)/)

    unless mentions.empty?
      mentions.flatten.each do |name|
        user = User.find_by username: name
        Mention.create(user: user, status_id: self.id) if user
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :statuses
  has_many :mentions
  has_many :unread_mentions, -> (obj) {where('viewed_at is NULL')}, class_name: :Mention, foreign_key: :user_id

  has_many :following_users, class_name: :Relationship, foreign_key: :leader_id
  has_many :followed_users, class_name: :Relationship, foreign_key: :follower_id

  has_many :followers, through: :following_users, source: :follower
  has_many :following, through: :followed_users, source: :leader

  validates :username, presence: true
  validates :email , presence: true
  validates :password, presence: true, length: {minimum: 5}

  has_secure_password

  def mark_unread_mentions!
    unread_mentions.each do |mention|
      mention.mark_viewed!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to root_path
    end
  end

  def wrong_path
    flash[:error] = "There was an error."
    redirect_to root_path
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @statuses = Status.where('body LIKE ?', "%##{params[:id]}%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new; end

  def create
    user = User.find_by email: params[:email]

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You are now logged in."
      redirect_to timeline_path
    else
      flash.now[:danger] = "There is something wrong with your username or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have now logged out."
    redirect_to root_path
  end
  
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :require_user

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(params.require(:status).permit(:body))
    @user = current_user
    @status.creator = @user

    if @status.save
      flash[:success] = "Your status has been created"
      redirect_to user_path(@user.username)
    else
      render :new
    end
  end

  def retweet
    status = Status.find(params[:id])
    new_status = Status.create(body: status.body, creator: current_user, parent_status: status)

    new_status.save ? flash[:success] = 'Retweeted!' : flash[:error] = 'Couldn\'t retweet!'
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:follow, :unfollow, :timeline, :mentions]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params.require(:user).permit(:username, :email, :password))

    if @user.save
      flash[:success] = "Your account has been created."
      session[:user_id] = @user.id
      redirect_to user_path(@user.username)
    else
      render :new
    end
  end

  def show
    @user = User.find_by username: params[:username]
    wrong_path unless @user
  end

  def follow
    user = User.find(params[:id])
    if user and current_user != user
      current_user.following << user
      redirect_to user_path(user.username)
      flash[:success] = "You are now following #{user.username}."
    else
      wrong_path
    end
  end

  def unfollow
    user = User.find(params[:id])
    rel = Relationship.where(follower_id: current_user.id, leader_id: user.id).first
    if user && rel
      rel.destroy
      redirect_to user_path(user.username)
      flash[:success] = "You've unfollowed #{user.username}."
    else
      wrong_path
    end
  end

  def timeline
    @statuses = []
    current_user.following.each do |user|
      @statuses << user.statuses
    end
    @statuses.flatten!
  end

  def mentions
    current_user.mark_unread_mentions!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auto_links(str)
    str = link_hashtag(str)
    str = link_mentions(str)
  end

  def link_hashtag(str)
    str.gsub(/#(\w+)/, "<a href='/hashtags/\\1'>#\\1</a>").html_safe
  end

  def link_mentions(str)
    str.gsub(/@(\w+)/, "<a href='/\\1'>@\\1</a>").html_safe
  end
end

app/views/hashtags/show.slim
=render 'shared/page_title', title: "Statuses for hashtag ##{params[:id]}"
=render @statuses

app/views/layouts/_msgs.slim
-flash.each do |type, msg|
  .alert class="alert-#{type == 'success' ? type : 'danger'}"
    a.close data-dismiss='alert' X
    div id="#{type}" = msg

app/views/layouts/_navbar.slim
nav.navbar.navbar-inverse role='navigation'
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar-collapse"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      =link_to 'Twit', root_path, class: 'navbar-brand'
    .navbar-collapse.collapse#navbar-collapse
      .nav.navbar-nav
        ul.nav.navbar-nav
          -if logged_in?
            li= link_to 'New Status', new_status_path
            li= link_to 'Timeline', timeline_path
            li= link_to "Mentions (#{current_user.unread_mentions.size})", mentions_path
            </ul>
            </div>
            ul.nav.navbar-nav.navbar-right
              li.dropdown
                a.dropdown-toggle href='#' data-toggle='dropdown' role='button' aria-expanded='false'
                  =current_user.username
                  span.caret<
                ul.dropdown-menu
                  li= link_to 'Account', user_path(current_user.username)
                  li= link_to 'Logout', logout_path
          -else
            li= link_to 'Register', new_user_path
            li= link_to 'Login', login_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Twit1
    = stylesheet_link_tag    :application, media: :all, 'data-turbolinks-track' => true
    = javascript_include_tag :application, 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      .row
        =render 'layouts/navbar'

      .row
        =render 'layouts/msgs'
        =yield

    %footer

app/views/layouts/application.slim
doctype html
html
  head
    title Twit1
    =stylesheet_link_tag    :application, media: :all, 'data-turbolinks-track' => true
    =javascript_include_tag :application, 'data-turbolinks-track' => true
    =csrf_meta_tags
  body
    =render 'layouts/navbar'

    .container-fluid
      =render 'layouts/msgs' if flash.keys.any?
      =yield

    footer

app/views/mentions/_mention.html.haml
.container
  .well.well-sm
    =mention.status.body
    %h5
      by
      =link_to mention.status.creator.username, mention.status.creator.username
      %small
        =time_ago_in_words mention.status.created_at
        ago

app/views/mentions/_mention.slim
=render mention.status

app/views/shared/_error_msg.html.haml
-if obj.errors.any?
  .container.text-center
    .alert.alert-danger
      The form contains
      =pluralize obj.errors.count, 'error'
      -obj.errors.full_messages.each do |msg|
        %br
        =msg

app/views/shared/_error_msg.slim
-if obj.errors.any?
  .container.text-center
    .alert.alert-danger
      ' The form contains
      =pluralize obj.errors.count, 'error'
      -obj.errors.full_messages.each do |msg|
        br
        =msg

app/views/shared/_page_title.slim
h4.text-center= title
hr.title

app/views/statuses/_status.html.haml
.container
  .well.well-sm
    %h4= status.body
    %h5
      =link_to status.creator.username, status.creator.username
      %small
        =time_ago_in_words status.created_at
        ago

app/views/statuses/_status.slim
.well.well-sm
  h4
    =auto_links(status.body)
  h5
    ' by
    -if status.retweet_id
      =link_to status.parent_status.creator.username, user_path(status.parent_status.creator.username)
      '  > Retweet by:
    =link_to status.creator.username, status.creator.username
    small<
      =time_ago_in_words status.created_at
      |  ago
  -if logged_in? && status.creator != current_user
    =link_to 'Retweet', retweet_status_path(status), method: :post

app/views/statuses/new.html.haml
=render 'shared/page_title', title: 'New status'
=render 'shared/error_msg', obj: @status

.container#form
  .well.col-md-8
    =form_for @status do |f|
      .form-group
        =f.label :body, "Status"
        =f.text_area :body, class:'form-control'

      =f.submit 'Submit', class: 'btn btn-success'

app/views/statuses/new.slim
=render 'shared/page_title', title: 'New status'
=render 'shared/error_msg', obj: @status
#form
  .well.col-xs-12.col-md-8
    =form_for @status do |f|
      .form-group
        =f.label :body, "Status"
        =f.text_area :body, class:'form-control'

      =f.submit 'Submit', class: 'btn btn-success'

app/views/users/_user.slim
.well.well-sm
  h4= link_to user.username, user.username
  h5
    ' followers:
    =user.followers.count
    '  following:
    =user.following.count

app/views/users/index.html.haml
=render 'shared/page_title', title: "Users"
=render @users

app/views/users/index.slim
=render 'shared/page_title', title: "Users"
=render @users

app/views/users/mentions.html.haml
=render 'shared/page_title', title: 'Mentions'
=render current_user.mentions

app/views/users/mentions.slim
=render 'shared/page_title', title: 'Mentions'
=render current_user.mentions

app/views/users/new.html.haml
=render 'shared/page_title', title: 'Register'
=render 'shared/error_msg', obj: @user

.container#form
  .well.col-md-6
    =form_for @user do |f|
      .form-group
        =f.label :username
        =f.text_field :username, class: 'form-control'

      .form-group
        =f.label :email
        =f.email_field :email, class: 'form-control'

      .form-group
        =f.label :password
        =f.password_field :password, class: 'form-control'

      .form-group
        =f.label :password_confirmation
        =f.password_field :password_confirmation, class: 'form-control'

      =f.submit 'Create', class: 'btn btn-success'

app/views/users/new.slim
=render 'shared/page_title', title: 'Register'
=render 'shared/error_msg', obj: @user
#form
  .well.col-xs-8.col-md-4
    =form_for @user do |f|
      .form-group
        =f.label :username
        =f.text_field :username, class: 'form-control'

      .form-group
        =f.label :email
        =f.email_field :email, class: 'form-control'

      .form-group
        =f.label :password
        =f.password_field :password, class: 'form-control'

      .form-group
        =f.label :password_confirmation
        =f.password_field :password_confirmation, class: 'form-control'

      =f.submit 'Create', class: 'btn btn-success'

app/views/users/show.html.haml
.container
  %h4
    =link_to @user.username, @user.username
  %h4
    -if logged_in?
      -unless current_user.following.include? @user
        =link_to '+ follow', follow_user_path(@user), method: :post
      -else
        =link_to '- unfollow', unfollow_user_path(@user), method: :post
  %p
    %ul
      =render @user.statuses

app/views/users/show.slim
=render 'shared/page_title', title: @user.username
h4
  -if logged_in?
    -unless current_user.following.include? @user
      =link_to '+ follow', follow_user_path(@user), method: :post
    -else
      =link_to '- unfollow', unfollow_user_path(@user), method: :post
=render @user.statuses.sort_by{|status| status.created_at}.reverse

app/views/users/timeline.html.haml
=render 'shared/page_title', title: "Timeline"

=render @statuses

app/views/users/timeline.slim
=render 'shared/page_title', title: "Timeline"
=render @statuses.sort_by{|status| status.created_at}.reverse